#!/bin/bash

a=$1
b=$2
out=$3

sort -n "$a" "$b" > "$out.presort"

/usr/bin/env ruby <<-RUBY
input="$out.presort"
output="$out"

current_value = nil
current_weight = nil
File.open(output, "wb") do |f|
    IO.readlines(input).each do |line|
        pieces = line.strip.split(/\s+/)
        value = pieces[0].to_f
        weight = pieces[1].to_i
        if value == current_value
            current_weight += weight
        else
            f.puts "#{current_value} #{current_weight}" if current_value
            current_value = value
            current_weight = weight
        end
    end
    f.puts "#{current_value} #{current_weight}"
end
RUBY

rm "$out.presort"
